### PR TITLE
Hello microverse

### PR DESCRIPTION
**Pull request by berylcl**
In this pull request, I was able to:
Create a branch hello-microverse
Create an index.html file and used a style.css file to style the contents of the h1 tag.
Create a 'gitignore file and added test.md and node_modules

### CODE REVIEW

**Review by nahnahdev — CHANGES_REQUESTED** [review]
Hi @berylcl, 

You've done well implementing some of the requested changes :clap:, but there are still some which haven't been well addressed.



 ## Highlights
:heavy_check_mark: Good use of GitHub flow
:heavy_check_mark: LInters are correctly setup and passing
:heavy_check_mark: Descriptive PR title

 ## Required Changes ♻️

- I noticed that you deleted the original branch you used for the project.

- **Please Note** that a branch should not be deleted midway through the review process. The initial branch you used as well as the initial pull request for the project is what must be used until the project is approved. Failure to do this can result in your project being invalidated in the future.

- Please make sure to make the requested changes and send back this same Pull request for another review.

- I also noticed that you are missing the  [Microverse Readme template](https://github.com/microverseinc/readme-template). This makes your project incomplete. Every section of the readme template is required with the exception of the FAQ section which is optional. So please make sure to add the README template to your project and fill in all the necessary contents :+1: Please remove the template logo, if you have your own logo you can replace it with it one, if not please delete it.

- Good job putting together a good title for your Pull request :100:  but the description is not well-put together. It should contain a short descriptive summary of the changes that were made in the current pull request. You can learn more about writing good pull requests [here](https://hugooodias.medium.com/the-anatomy-of-a-perfect-pull-request-567382bb6067).

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by osamaashraf6 — CHANGES_REQUESTED** [review]
Hi  @berylcl ☺️, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

you-are-near

## Highlights ✔️
- [x] Good commit messages.
- [x] Descriptive READme file in a professional way.
- [x] Good usage in correcting GitHub flow

 ## Required Changes ♻️

- [ ] You have implemented the required changes by the previous reviewer but while you made them there is a conflict in your branch that make the linters not appear, so kindly fix the conflict and make sure the linters are green.

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by franclobo — CHANGES_REQUESTED** [review]
Hi @berylcl, 

# ♻️ REQUIRED CHANGES ♻️ 

so-close-jim-halpert

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Correct Github flow ✔️ 
- Professional README file ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

- [ ] As the last code reviewer suggested:

> You have implemented the required changes by the previous reviewer but while you made them there is a conflict in your branch that make the linters not appear, so kindly fix the conflict and make sure the linters are green.

- [ ] Please 🙏🏽 review the linters to complete the general requirements 👉🏽 Make sure that there are [no linter errors](https://github.com/microverseinc/linters-config). 👈🏽 you should see the result of the GitHub actions checks:

| Expected | Your repo |
|---|---|
| image | image |



## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
# _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by ichala — APPROVED** [review]
Hi @berylcl   ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966

# To Highlight 💪🏻

- Changes Implemented ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
